### ISSUE TITLE
Ease of Providing Additional OS Support?

### ISSUE THREAD

**Issue by githubquestions** [d0iasm/rvemu#1]
This is a super cool project. I am curious how difficult it would be to support other operating systems (specifically curious about [TockOS](https://github.com/tock/tock), which increasingly runs on RISC-V boards, but also interested in general portability).

**Comment by d0iasm** [comment]
To support other operating systems, you need to add peripheral devices in `src/devices/*` and map them to specific addresses in `src/bus.rs`. I believe it should work well if other parts don't have mistakes.

However, for now, this project is really specific for `xv6` so there might be missing implementation in CPU or CSRs.

I'm trying to support Linux as a next step, so this project will be more mature and make it easier to support other operating systems.
