### ISSUE TITLE
"Index out of bounds" at virtio.rs when running xv6 on browser

### ISSUE THREAD

**Issue by jahzielv** [d0iasm/rvemu#3]
I built the project for the browser, and started it up with no issues. However, when I ran `run xv6`, I get an "Index out of bounds" error in the console, which is traced back to `virtio.rs`. This causes xv6 to never boot up. I've attached a screenshot of the page and DevTools open side by side. I'm running rvemu in Chrome 80. Thanks for your help!
![Screen Shot 2020-04-08 at 12 46 41 PM](https://user-images.githubusercontent.com/19838370/78908483-241bde80-7a50-11ea-914c-4e4db8168c24.png)

**Comment by d0iasm** [comment]
Thank for your issue.

I can't reproduce your problem in my environment. Can you clear browser cache data? I sometimes pushed files with bugs without couldn't notice them, but I did fix them later. The browser might cache the files with bugs.

If you're using Chrome, you can clear them in `chrome://settings/?search=cache`.

**Comment by jahzielv** [comment]
This did the trick! Thank you!
