### ISSUE TITLE
Question: possible to expose a canvas element as a framebuffer-like device?

### ISSUE THREAD

**Issue by bbarker** [d0iasm/rvemu#4]
First, I'd just like to say - amazing project! I hope to try it out with a modified xv6 at some point.

It might be an interesting experiment to try, and provide the possibility to do some interesting graphics from RISC-V OSes, but I must admit I am quite out of my depth here at the moment, and it isn't a feature I'm anticipating to want to try anytime soon.

**Comment by bbarker** [comment]
I just realized (having not checked on it for years) that JSLinux has undergone [a lot of change](https://bellard.org/jslinux/tech.html), including [RISC-V support and X-Windows support](https://bellard.org/jslinux/). Sorry if you already knew about all this, but just thought I would share in case some of the graphics and performance optimizations used by that project might be of interest.

**Comment by d0iasm** [comment]
Thank you for your question and information!

I don't have a plan to support graphics and don't know how to do it yet. The idea, however, definitely sounds great. I will try it out after completing Linux support.

Thanks!
